makelib cclib/new:3
ccmain/rel
iolib1/rel
iolib2/rel
iolib3/rel
calloc/rel
malloc/rel
printf/rel
atoi/rel
dtoi/rel
itoa/rel
itoab/rel
reverse/rel
strlen/rel
scanf/rel
utoi/rel
ctype/rel
getarg/rel
string1/rel
string2/rel
string3/rel
floatsim/rel
circle/rel
romlib1/rel
romlib2/rel
romlib3/rel
stop
/./1 enter when all ok
kill cclibold/rel:3
rename cclib/rel:3 cclibold/rel
rename cclib/new:3
 cclib/rel
